#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-junit
Version  : 3.8.1
Release  : 10
URL      : https://repo1.maven.org/maven2/junit/junit/3.8.1/junit-3.8.1.jar
Source0  : https://repo1.maven.org/maven2/junit/junit/3.8.1/junit-3.8.1.jar
Source1  : https://repo.maven.apache.org/maven2/junit/junit/4.11/junit-4.11.pom
Source2  : https://repo.maven.apache.org/maven2/junit/junit/4.4/junit-4.4.jar
Source3  : https://repo.maven.apache.org/maven2/junit/junit/4.4/junit-4.4.pom
Source4  : https://repo.maven.apache.org/maven2/junit/junit/4.6/junit-4.6-sources.jar
Source5  : https://repo.maven.apache.org/maven2/junit/junit/4.6/junit-4.6.jar
Source6  : https://repo.maven.apache.org/maven2/junit/junit/4.6/junit-4.6.pom
Source7  : https://repo1.maven.org/maven2/junit/junit/3.8.1/junit-3.8.1.pom
Source8  : https://repo1.maven.org/maven2/junit/junit/3.8.2/junit-3.8.2.jar
Source9  : https://repo1.maven.org/maven2/junit/junit/3.8.2/junit-3.8.2.pom
Source10  : https://repo1.maven.org/maven2/junit/junit/4.10/junit-4.10.jar
Source11  : https://repo1.maven.org/maven2/junit/junit/4.10/junit-4.10.pom
Source12  : https://repo1.maven.org/maven2/junit/junit/4.11/junit-4.11.jar
Source13  : https://repo1.maven.org/maven2/junit/junit/4.11/junit-4.11.pom
Source14  : https://repo1.maven.org/maven2/junit/junit/4.12/junit-4.12.jar
Source15  : https://repo1.maven.org/maven2/junit/junit/4.12/junit-4.12.pom
Source16  : https://repo1.maven.org/maven2/junit/junit/4.8.1/junit-4.8.1.jar
Source17  : https://repo1.maven.org/maven2/junit/junit/4.8.1/junit-4.8.1.pom
Source18  : https://repo1.maven.org/maven2/junit/junit/4.8.2/junit-4.8.2.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : CPL-1.0
Requires: mvn-junit-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-junit package.
Group: Data

%description data
data components for the mvn-junit package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/junit/junit/3.8.1
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/junit/junit/4.11
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/junit/junit/4.11/junit-4.11.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/junit/junit/4.4
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/junit/junit/4.4/junit-4.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/junit/junit/4.4
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/junit/junit/4.4/junit-4.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/junit/junit/4.6
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/junit/junit/4.6/junit-4.6-sources.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/junit/junit/4.6
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/junit/junit/4.6/junit-4.6.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/junit/junit/4.6
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/junit/junit/4.6/junit-4.6.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/junit/junit/3.8.1
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/junit/junit/3.8.1/junit-3.8.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/junit/junit/3.8.2
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/junit/junit/3.8.2/junit-3.8.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/junit/junit/3.8.2
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/junit/junit/3.8.2/junit-3.8.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/junit/junit/4.10
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/junit/junit/4.10/junit-4.10.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/junit/junit/4.10
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/junit/junit/4.10/junit-4.10.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/junit/junit/4.11
cp %{SOURCE12} %{buildroot}/usr/share/java/.m2/repository/junit/junit/4.11/junit-4.11.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/junit/junit/4.11
cp %{SOURCE13} %{buildroot}/usr/share/java/.m2/repository/junit/junit/4.11/junit-4.11.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/junit/junit/4.12
cp %{SOURCE14} %{buildroot}/usr/share/java/.m2/repository/junit/junit/4.12/junit-4.12.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/junit/junit/4.12
cp %{SOURCE15} %{buildroot}/usr/share/java/.m2/repository/junit/junit/4.12/junit-4.12.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/junit/junit/4.8.1
cp %{SOURCE16} %{buildroot}/usr/share/java/.m2/repository/junit/junit/4.8.1/junit-4.8.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/junit/junit/4.8.1
cp %{SOURCE17} %{buildroot}/usr/share/java/.m2/repository/junit/junit/4.8.1/junit-4.8.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/junit/junit/4.8.2
cp %{SOURCE18} %{buildroot}/usr/share/java/.m2/repository/junit/junit/4.8.2/junit-4.8.2.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar
/usr/share/java/.m2/repository/junit/junit/3.8.1/junit-3.8.1.pom
/usr/share/java/.m2/repository/junit/junit/3.8.2/junit-3.8.2.jar
/usr/share/java/.m2/repository/junit/junit/3.8.2/junit-3.8.2.pom
/usr/share/java/.m2/repository/junit/junit/4.10/junit-4.10.jar
/usr/share/java/.m2/repository/junit/junit/4.10/junit-4.10.pom
/usr/share/java/.m2/repository/junit/junit/4.11/junit-4.11.jar
/usr/share/java/.m2/repository/junit/junit/4.11/junit-4.11.pom
/usr/share/java/.m2/repository/junit/junit/4.12/junit-4.12.jar
/usr/share/java/.m2/repository/junit/junit/4.12/junit-4.12.pom
/usr/share/java/.m2/repository/junit/junit/4.4/junit-4.4.jar
/usr/share/java/.m2/repository/junit/junit/4.4/junit-4.4.pom
/usr/share/java/.m2/repository/junit/junit/4.6/junit-4.6-sources.jar
/usr/share/java/.m2/repository/junit/junit/4.6/junit-4.6.jar
/usr/share/java/.m2/repository/junit/junit/4.6/junit-4.6.pom
/usr/share/java/.m2/repository/junit/junit/4.8.1/junit-4.8.1.jar
/usr/share/java/.m2/repository/junit/junit/4.8.1/junit-4.8.1.pom
/usr/share/java/.m2/repository/junit/junit/4.8.2/junit-4.8.2.pom
